# Generated by Django 5.0.7 on 2024-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeinsurance',
            name='plans',
            field=models.CharField(choices=[('health', 'health'), ('car', 'car'), ('home', 'home'), ('life', 'life')], max_length=20),
        ),
    ]
